### ISSUE TITLE
Script scénario

### ISSUE THREAD

**Issue by Shinrod** [Shinrod/RPG-EMA#2]
Ici on discute du scénario

**Comment by emmalacaille** [comment]
Nouvel élève à l’EMA
premier matin: 
rencontre avec qques persos (1 ou 2 amis + 1 méchant)
speech de Thierry de M (chapeau)
premier cours (RDM=restriction de la magie)

midi:
perso se perd en allant au self, trouve premier pentagramme, arrive dans monde corrompu, affronte petit monstre, plein d’autres arrivent et il s’enfuit par le portail qui ensuite disparaît

premier après-midi: choix entre plusieurs activités ?
cours
fabriquer objets/potions
parler à (recruter ?) des gens

soir:
soirée donc bourré (commandes inversées si on a le temps)
rencontre avec le méchant
