### ISSUE TITLE
Se renseigner sur LibGDX et voir comment l'utiliser dans notre projet

### ISSUE THREAD

**Issue by Shinrod** [Shinrod/RPG-EMA#4]
La librairie pour coder le jeu proposée par le prof

**Comment by Shinrod** [comment]
Lien vers un tuto qui semble assez complet (j'ai pas regardé plus en détails encore) :

https://www.gamefromscratch.com/page/LibGDX-Tutorial-series.aspx

**Comment by VarnMeutch** [comment]
https://tuto-libgdx.blogspot.com/?view=classic

**Comment by VarnMeutch** [comment]
Un tuto FR

**Comment by VarnMeutch** [comment]
https://github.com/libgdx/libgdx/wiki
c'est le Wiki de libgdx

**Comment by Shinrod** [comment]
https://www.youtube.com/watch?v=YCGmXVCvogY&list=PLrnO5Pu2zAHKAIjRtTLAXtZKMSA6JWnmf&index=1
Un tuto vidéo
Je sais pas ce que ça donne, je le regarde ce soir

**Comment by Shinrod** [comment]
https://www.gamedevelopment.blog/full-libgdx-game-tutorial-project-setup/
Un tuto écrit qui a l'air assez complet
